### ISSUE TITLE
Black screen after title screen on SD2SNES

### ISSUE THREAD

**Issue by GinBunBun** [mlarouche/TopGear2-MSU1#1]
Every rom I have tried goes to a black screen and gets stuck there after the title screen how ever the MSU 1 music still plays in the background. Is there a specific rom I need to use?

**Comment by mlarouche** [comment]
Does the ROM you use has a header ? This is the ROM I use

TOP GEAR 2
U.S.A.
1048576 Bytes (8.0000 Mb)
Padded: No
Interleaved/Swapped: No
Backup unit/emulator header: No
Internal size: 8 Mb
Version: 1.0
Checksum: Ok, 0x1cd4 (calculated) == 0x1cd4 (internal)
Inverse checksum: Ok, 0xe32b (calculated) == 0xe32b (internal)
Checksum (CRC32): 0x2b88bee8

**Comment by GinBunBun** [comment]
Ah I will see if it does. I didn't think of that.

**Comment by GinBunBun** [comment]
It didnt have a header. I tried different roms both with and without headers nothing works. it just stays at that black screen while the music plays. Can I have the rom you used?

**Comment by mlarouche** [comment]
Did you find a ROM with the same checksum I gave ?

**Comment by GinBunBun** [comment]
Yeah I did it didn't help. Tried with a header and without. I'm assuming that it works fine on Higan and Bsnes but not the sd2snes. There must be some kind of issue. I also tried different firmwares on the sd2snes. Nothing worked.

**Comment by GinBunBun** [comment]
I tried everything again from the above message this time with the IPS patch from romhacking.net. Same issue as before. Any idea what's wrong?

**Comment by mlarouche** [comment]
weird because I did test my hack on a SD2SNES without any issues. Contact me in private, I'll send you the ROM I used.

**Comment by GinBunBun** [comment]
I don't understand why it doesn't work for me.. I tried multiple cards. Nothing works. It's very weird.

**Comment by kurrono** [comment]
Format ur sdcard but saves ur files u need a special app that erases the sdcard with overwrite...not full or quick..is overwrite..so ur sdcard becomes faster

**Comment by teamvb** [comment]
i get black screen with music after i finish the first race ,my sd2snes read  sd acc. time:0.302 / 0.537 ms avg/max 
,a few people is having black screen too on the forum http://krikzz.com/forum/index.php?topic=2582.30#msg29271 ,oh thank you very much for making  msu1 hacks for the world to enjoy

**Comment by mlarouche** [comment]
Closed in 0d91aa52556afc6736c020fb0cad1d02de9591da :)

**Comment by mlarouche** [comment]
Now updated with the fix at romhacking.net :) http://www.romhacking.net/hacks/2389/

**Comment by kurrono** [comment]
Hey DarkShock,i believe ugoin to finsih chrono trigger..then thenext step maybe Act Raiser,man ur a pro on assembly i wanna hack myself f-zero..igot the pcm done already..only hack thegame.is left to do

**Comment by teamvb** [comment]
Thank you very much for the fix, after dinner I am going to play top gear 2 msu1
